### ISSUE TITLE
WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable

### ISSUE THREAD

**Issue by danielbonnell** [icco/instagram-continued#12]
Hello,

I am receiving the following warning when accessing the API. The warning seems to be repeated multiple times (once per each post returned). 

```client.get("/v1/users/#{account_id}/media/recent")```

```W, [2017-03-08T09:00:26.652732 #14007]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.```

This doesn't seem to be causing any breakages. Just documenting it in case any one else runs into it. I might try to put together a PR this weekend on it.

**Comment by icco** [comment]
Fixed.

**Comment by manikkang** [comment]
still getting this warning

**Comment by icco** [comment]
@manikkang see https://github.com/icco/instagram-continued/issues/15
